[package]
name = "rslabs"
version = "0.1.0"
authors = ["LinkWu <wjianl@qq.com>"]
edition = "2018"
default-run = "rslabs"

[workspace]
members = ["btcodec", "btseed", "book", "c2rs", "elf", "light2d", "pxm", "riscv", "stdoor"]

[features]

[dependencies]
