[package]
name = "c2rs"
version = "0.1.0"
authors = ["LinkWu <wjianl@qq.com>"]
edition = "2018"
build = "build.rs"
workspace = ".."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cc = "1.0.46" 
