[package]
name = "book"
version = "0.1.0"
authors = ["LinkWu <wjianl@qq.com>"]
edition = "2018"
default-run = "chapter001"
workspace = ".."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
